# Generated by Django 3.2.6 on 2021-08-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoCrudApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='comment',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user_details',
            field=models.CharField(max_length=255),
        ),
    ]
